server:
  port: 80
#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/caro2o?serverTimezone=UTC&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath:mapper/**
  type-aliases-package: com.accp.caro2o.entity